In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sys

In [3]:
inputs=[1,2,3,2.5]

weights1=[0.2,0.8,-0.5,1.0]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[-0.26,-0.27,0.17,0.87]


bias1=2
bias2=3
bias3=0.5

outputs=[inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
        inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] +  bias2,
        inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] +  bias3]

print(outputs)


[4.8, 1.21, 2.385]


In [4]:
weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

print(list(zip(biases,weights)))

[(2, [0.2, 0.8, -0.5, 1.0]), (3, [0.5, -0.91, 0.26, -0.5]), (0.5, [-0.26, -0.27, 0.17, 0.87])]


In [5]:
#trying out dotproduct

import numpy as np

inputs=[1,2,3,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias= 2

output =np.dot(weights,inputs) +  bias
print(output)



4.8


In [6]:
inputs=[1,2,3,2.5]

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

outputs=np.dot(weights,inputs) +  biases

#no.dot(weights,inputs) = [np.dot(weight[0],inputs),np.dot(weight[1],inputs),np.dot(weight[2],inputs) ] 

print(outputs)

[4.8   1.21  2.385]


In [8]:
#using batches 

inputs=[[1,2,3,2.5],
        [2,5,1,2],
        [-1.5,2.7,3.3,-0.8]]

weights =[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

#weights is (3X4) and inputs is also (3X4), so we need to transpose the inputs matrix for multiplication
output = np.dot(weights,np.array(inputs).T) + biases
print(output)

[[ 4.8    8.9   -0.09 ]
 [ 0.21  -1.29  -1.449]
 [ 3.885  3.04   0.026]]


In [14]:


weights2 = [[0.1,-0.14,0.5],
            [-0.5,0.12,-0.33],
            [-0.44,0.73,-0.13]]

biases2 = [-1,2,-0.5]

layer1_outputs = np.dot(inputs,np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs , np.array(weights2).T) + biases2 

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2406  -2.283   -4.9879 ]
 [-0.99314  1.41254 -0.35655]]


In [26]:
#converting inputs into objects for cleaner and more dynamic code 
import numpy as np

X = [[1,2,3,2.5],
    [2,5,1,2],
    [-1.5,2.7,3.3,-0.8]]

np.random.seed(0)

class Layer_Dense :
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.10*np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))

    def forward(self,inputs):
        self.output=(np.dot(inputs,self.weights)) + self.biases

layer1=Layer_Dense(4,5)
layer2=Layer_Dense(5,5)
layer3=Layer_Dense(5,2)

layer1.forward(X)
#print(layer1.output)

layer2.forward(layer1.output)
#print(layer2.output)


layer3.forward(layer2.output)
print(layer3.output)


[[-0.00126082  0.01375158]
 [ 0.00545449  0.01595045]
 [ 0.00295563  0.01087262]]
